# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Staghorn < Formula
  desc "A shared team layer for Claude Code - syncs team CLAUDE.md guidelines from GitHub"
  homepage "https://github.com/HartBrook/staghorn"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.3.0/staghorn_0.3.0_darwin_amd64.tar.gz"
      sha256 "f38172da03e7d2879373e2742150467309ca53f9c45dfd9116619285dc6d390a"

      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.3.0/staghorn_0.3.0_darwin_arm64.tar.gz"
      sha256 "d318aaba1d1c34e3cd3a7910c949a952616709a975de716e72fa82334e905a52"

      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.3.0/staghorn_0.3.0_linux_amd64.tar.gz"
      sha256 "9505cfb813be0f66878faf60b4a1895ce480a19627919aec2c5fbd6077cff4ae"
      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.3.0/staghorn_0.3.0_linux_arm64.tar.gz"
      sha256 "5ad1c7a146ea9ad1b21c05781302bf823044263d907af8c7896306642420ddf7"
      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
  end

  test do
    system "#{bin}/staghorn", "--version"
  end
end
