# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Staghorn < Formula
  desc "A shared team layer for Claude Code - syncs team CLAUDE.md guidelines from GitHub"
  homepage "https://github.com/HartBrook/staghorn"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.8.0/staghorn_0.8.0_darwin_amd64.tar.gz"
      sha256 "26df8646e9e3b2e745663875f9d962695a820d5e63b177dda16e425b5ee46329"

      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.8.0/staghorn_0.8.0_darwin_arm64.tar.gz"
      sha256 "ba9cd0fd896b621a9ae5e1cb02902a64c87685701a223925bd8118417eb04774"

      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.8.0/staghorn_0.8.0_linux_amd64.tar.gz"
      sha256 "65b17bde061568a118ca6262829edf4bead7b87f13412e0b2116d9ee12ae2fa4"
      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.8.0/staghorn_0.8.0_linux_arm64.tar.gz"
      sha256 "1fa0b8fc739f85e2bdd3ecce9a9015fa0b756b1814eebce1f1373016e81bb931"
      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
  end

  test do
    system "#{bin}/staghorn", "--version"
  end
end
