# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Staghorn < Formula
  desc "A shared team layer for Claude Code - syncs team CLAUDE.md guidelines from GitHub"
  homepage "https://github.com/HartBrook/staghorn"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.1.0/staghorn_0.1.0_darwin_amd64.tar.gz"
      sha256 "c9806206417ec856b1e14e628c833cfb1189c17f0c9861a33104c6eeadb237bc"

      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.1.0/staghorn_0.1.0_darwin_arm64.tar.gz"
      sha256 "e1dfd768ecc57798f47deccaf2a27540aa02d9d0bee72e99e2796bfad5c48603"

      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.1.0/staghorn_0.1.0_linux_amd64.tar.gz"
      sha256 "9af53e2ddedb141f7cce7abb3a5359d26ee2a68aa00e125d46d3ac4488a48820"
      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HartBrook/staghorn/releases/download/v0.1.0/staghorn_0.1.0_linux_arm64.tar.gz"
      sha256 "19e3b4822cf5b840bdcea8e4d6d6cba60dcb8fe60e696d10567c810004340563"
      def install
        bin.install "staghorn"
        bin.install_symlink "staghorn" => "stag"
      end
    end
  end

  test do
    system "#{bin}/staghorn", "--version"
  end
end
